config/routes.rb
Rails.application.routes.draw do

  
  root 'welcome#index'
  resources :containers do
  	resources :measures, only: [:create,:destroy,:update,:show]
  end
  get 'containers/:id/metrics', to: "containers#metrics"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/container.rb
class Container < ApplicationRecord
	has_many :measures, :dependent => :destroy
end

app/models/measure.rb
class Measure < ApplicationRecord
  belongs_to :container
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
end

app/controllers/containers_controller.rb
class ContainersController < ApplicationController
  before_action :set_container, only: [:show, :edit, :update, :destroy, :metrics]

  # GET /containers
  # GET /containers.json
  def index
    @containers = Container.all
  end

  # GET /containers/1
  # GET /containers/1.json
  def show
  end

  # GET /containers/new
  def new
    @container = Container.new
  end

  # GET /containers/1/edit
  def edit
  end

  def metrics
    @measures = @container.measures
  end

  # POST /containers
  # POST /containers.json
  def create

    @container = Container.new(container_params)

    @container.volume = (Math::PI * @container.radius * @container.radius * @container.height * 1000).round(2)


    respond_to do |format|
      if @container.save
        format.html { redirect_to @container, notice: 'Container was successfully created.' }
        format.json { render :show, status: :created, location: @container }
      else
        format.html { render :new }
        format.json { render json: @container.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /containers/1
  # PATCH/PUT /containers/1.json
  def update

    respond_to do |format|
      if @container.update(container_params)
        @container.volume = (Math::PI * @container.radius * @container.radius * @container.height * 1000).round(2)
        @container.save
        format.html { redirect_to @container, notice: 'Container was successfully updated.' }
        format.json { render :show, status: :ok, location: @container }
      else
        format.html { render :edit }
        format.json { render json: @container.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /containers/1
  # DELETE /containers/1.json
  def destroy
    @container.destroy
    respond_to do |format|
      format.html { redirect_to containers_url, notice: 'Container was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_container
      @container = Container.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def container_params
      params.require(:container).permit(:name, :radius, :height, :volume)
    end
end

app/controllers/measures_controller.rb
class MeasuresController < ApplicationController
  before_action :set_measure, only: [:show, :edit, :update, :destroy]
  before_action :set_container

  # GET /measures
  # GET /measures.json
  def index
    @measures = Measure.all
  end

  # GET /measures/1
  # GET /measures/1.json
  def show
  end

  # GET /measures/new
  def new
    @measure = Measure.new
  end

  # GET /measures/1/edit
  def edit
  end

  # POST /measures
  # POST /measures.json
  def create

    @measure = Measure.new(measure_params)
    @measure.container = @container
    volume = Math::PI * @measure.container.radius * @measure.container.radius * (@measure.height/100)
    volume *= 1000
    @measure.water_quantity = (@measure.container.volume - volume).round(2)

    respond_to do |format|
      if @measure.save
        format.html { redirect_to @measure.container, notice: 'Measure was successfully created.' }
        format.json { render :show, status: :created, location: @measure.container }
      else
        format.html { render :new }
        format.json { render json: @measure.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /measures/1
  # PATCH/PUT /measures/1.json
  def update
    respond_to do |format|
      if @measure.update(measure_params)
        format.html { redirect_to @measure, notice: 'Measure was successfully updated.' }
        format.json { render :show, status: :ok, location: @measure }
      else
        format.html { render :edit }
        format.json { render json: @measure.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /measures/1
  # DELETE /measures/1.json
  def destroy
    @measure.destroy
    respond_to do |format|
      format.html { redirect_to measures_url, notice: 'Measure was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_container
      @container=Container.find(params[:container_id])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_measure
      @measure = Measure.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def measure_params
      params.require(:measure).permit(:container_id, :height, :water_quantity)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/containers_helper.rb
module ContainersHelper
end

app/helpers/measures_helper.rb
module MeasuresHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/containers/_form.html.erb
<%= form_for(container) do |f| %>
  <% if container.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(container.errors.count, "error") %> prohibited this container from being saved:</h2>

      <ul>
      <% container.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :radius %>
    <%= f.text_field :radius %>
  </div>

  <div class="field">
    <%= f.label :height %>
    <%= f.text_field :height %>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/containers/edit.html.erb
<h1>Editar tinaco</h1>

<%= render 'form', container: @container %>

<%= link_to 'Ver', @container %> |
<%= link_to 'Regresar', containers_path %>

app/views/containers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Containers</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Radio</th>
      <th>Altura</th>
      <th>Volumen</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @containers.each do |container| %>
      <tr>
        <td><%= container.name %></td>
        <td><%= container.radius %></td>
        <td><%= container.height %></td>
        <td><%= container.volume %></td>
        <td><%= link_to 'Ver', container %></td>
        <td><%= link_to 'Editar', edit_container_path(container) %></td>
        <td><%= link_to 'Eliminar', container, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo tinaco', new_container_path %>

app/views/containers/metrics.html.erb
<h4>Promedio de agua el día de hoy</h4>
<%= line_chart @measures.group_by_hour_of_day(:created_at, range: 0.weeks.ago.midnight..Time.now, time_zone: "Central Time (US & Canada)", format: "%-l %P").average(:water_quantity), discrete: true, xtitle: "Hora", ytitle: "Litros"%>

<h4>Promedio de agua esta semana</h4>
<%= column_chart @measures.group_by_day_of_week(:created_at, range: 0.weeks.ago.midnight..Time.now,time_zone: "Central Time (US & Canada)", format: "%a").average(:water_quantity),discrete: true, xtitle: "Día de la semana", ytitle: "Litros"%>

<h4>Promedio de agua en el mes</h4>
<%= line_chart @measures.group_by_day_of_month(:created_at, range: 0.month.ago.midnight..Time.now,time_zone: "Central Time (US & Canada)",format: "%b %-e").average(:water_quantity), discrete: true, xtitle: "Día del mes", ytitle: "Litros" %>

<h4>Promedio de agua en el mes por dia</h4>
<%= column_chart @measures.group_by_day_of_week(:created_at, range: 4.month.ago.midnight..Time.now,time_zone: "Central Time (US & Canada)",format: "%a").average(:water_quantity), discrete: true, xtitle: "Día de la semana", ytitle: "Litros" %>

<h4>Promedio de agua por mes en el año</h4>
<%= column_chart @measures.group_by_month(:created_at, range: 0.year.ago.midnight..Time.now,time_zone: "Central Time (US & Canada)", format: "%b %Y").average(:water_quantity), discrete: true, xtitle: "Mes", ytitle: "Litros" %>

app/views/containers/new.html.erb
<h1>New Container</h1>

<%= render 'form', container: @container %>

<%= link_to 'Back', containers_path %>

app/views/containers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @container.name %>
</p>

<p>
  <strong>Radio:</strong>
  <%= @container.radius %>
</p>

<p>
  <strong>Altura:</strong>
  <%= @container.height %>
</p>

<p>
  <strong>Volumen en litros:</strong>
  <%= @container.volume %>
</p>

<p>
  <strong>Fecha de creación:</strong>
  <%= @container.created_at %>
</p>

<p>
  <%= link_to "Metricas", :controller => "containers", :action => "metrics", :id => @container %>
</p>



<div class="field">

  <h3>Mediciones</h3>
  <ul>
    <% @container.measures.each do |measure| %>
    <li>
      Cantidad de agua: <%= measure.water_quantity %> litros ------- [Medido el: <%= measure.created_at %>]
    </li> 
    <% end %>
  </ul>
  
</div>



<%= link_to 'Edit', edit_container_path(@container) %> |
<%= link_to 'Back', containers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tinaco</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/measures/_form.html.erb
<%= form_for(measure) do |f| %>
  <% if measure.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(measure.errors.count, "error") %> prohibited this measure from being saved:</h2>

      <ul>
      <% measure.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :container_id %>
    <%= f.text_field :container_id %>
  </div>

  <div class="field">
    <%= f.label :height %>
    <%= f.text_field :height %>
  </div>

  <div class="field">
    <%= f.label :water_quantity %>
    <%= f.text_field :water_quantity %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/measures/edit.html.erb
<h1>Editing Measure</h1>

<%= render 'form', measure: @measure %>

<%= link_to 'Show', @measure %> |
<%= link_to 'Back', measures_path %>

app/views/measures/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Measures</h1>

<table>
  <thead>
    <tr>
      <th>Container</th>
      <th>Height</th>
      <th>Water quantity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @measures.each do |measure| %>
      <tr>
        <td><%= measure.container %></td>
        <td><%= measure.height %></td>
        <td><%= measure.water_quantity %></td>
        <td><%= link_to 'Show', measure %></td>
        <td><%= link_to 'Edit', edit_measure_path(measure) %></td>
        <td><%= link_to 'Destroy', measure, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/measures/new.html.erb
<h1>New Measure</h1>

<%= render 'form', measure: @measure %>

<%= link_to 'Back', measures_path %>

app/views/measures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Container:</strong>
  <%= @measure.container %>
</p>

<p>
  <strong>Height:</strong>
  <%= @measure.height %>
</p>

<p>
  <strong>Water quantity:</strong>
  <%= @measure.water_quantity %>
</p>

<%= link_to 'Edit', edit_measure_path(@measure) %> |
<%= link_to 'Back', measures_path %>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>